### ISSUE TITLE
Type AppUIBSiteMap_subscription must define one or more fields.

### ISSUE THREAD

**Issue by praphullsa** [ServiceNowNextExperience/graphiql#2]
Hi,

Getting below error while doing Introspection,

      "message": "Type AppUIBSiteMap_subscription must define one or more fields.",
      "extensions": {},
      "stack": "GraphQLError: Type AppUIBSiteMap_subscription must define one or more fields.\n    at SchemaValidationContext.reportError (https://unpkg.com/graphiql/graphiql.min.js:32215:23)\n    at validateFields (https://unpkg.com/graphiql/graphiql.min.js:32326:13)\n    at validateTypes (https://unpkg.com/graphiql/graphiql.min.js:32300:7)\n    at Object.validateSchema (https://unpkg.com/graphiql/graphiql.min.js:32190:3)\n    at https://unpkg.com/graphiql/graphiql.min.js:64452:46\n    at updateMemo (https://unpkg.com/react-dom@17/umd/react-dom.development.js:15897:21)\n    at Object.useMemo (https://unpkg.com/react-dom@17/umd/react-dom.development.js:16443:18)\n    at Object.useMemo (https://unpkg.com/react@17/umd/react.development.js:1557:23)\n    at SchemaContextProvider (https://unpkg.com/graphiql/graphiql.min.js:64452:15)\n    at renderWithHooks (https://unpkg.com/react-dom@17/umd/react-dom.development.js:15015:20)"
    }

**Comment by bravogolfgolf** [comment]
I am receiving the same error when opening the Document Explorer in graphiql:

Schema is invalid: Type AppUIBSiteMap_subscription must define one or more fields.

Build name: Utah
Build date: 10-10-2023_1258
Build tag: glide-utah-12-21-2022__patch7a-09-28-2023

graphiql seems to be working as designed except for Document Explorer.

![graphiql](https://github.com/ServiceNowNextExperience/graphiql/assets/2632121/36e3a43c-cd08-4e70-b53c-9101052efa83)
![properties](https://github.com/ServiceNowNextExperience/graphiql/assets/2632121/3e32ac12-6ba7-4d12-a706-4a7684f029e7)
